#####################################
####                             ####
####      Chash Base Config      ####
####                             ####
#####################################
# 日志级别
# silent / info / warning / error / debug
log-level: silent
# HTTP 代理端口
port: 61081
# SOCKS5 代理端口
socks-port: 61080
# Redir 代理端口
# redir-port: 7892
# RESTful API
external-controller: 127.0.0.1:61090
# 规则模式
# Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule
allow-lan: false

#####################################
####                             ####
####          Chash DNS          ####
####                             ####
#####################################
# enhanced-mode: NORMAL(normal) / FAKEIP(fakeip) / MAPPING(redir-host)
dns:
  enable: false
  ipv6: false
  listen: 127.0.0.1:53
  default-nameserver:
    - 119.29.29.29
    - 182.254.116.116
  enhanced-mode: fake-ip #redir-host or fake-ip
  # fake-ip-range: 198.18.0.1/16
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com
  nameserver:
    - tls://adguard.wither.ivenfe.cc
  fallback:
    - tls://8.8.4.4:853
    - tls://1.1.1.1:853

#####################################
####                             ####
####     Chash Proxy Config      ####
####                             ####
#####################################

proxy-providers:
  proxies:
    type: file
    path: ./proxies/default.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: PROXY
    type: select
    use:
      - proxies

#####################################
####                             ####
####      Chash Rule Config      ####
####                             ####
#####################################

rules:
##########################
####      屏蔽域名     ####
##########################
## Block
  - DOMAIN-SUFFIX, vortex.data.microsoft.com, REJECT

##########################
####   环路局域网直连   ####
##########################
## LAN
  - DOMAIN-SUFFIX, local, DIRECT
  - IP-CIDR, 127.0.0.0/8, DIRECT
  - IP-CIDR, 192.168.0.0/16, DIRECT
  - DOMAIN-SUFFIX, lan.slime.ivenfe.cc, DIRECT

## Proxies
  - DOMAIN-SUFFIX, tunnel.doven.best, DIRECT

## Server
  - DOMAIN-SUFFIX, 2933637.xyz, DIRECT

## V2EX
  - DOMAIN-SUFFIX, v2ex.com, DIRECT
## 职称网
  - DOMAIN-SUFFIX, sacee.org.cn, DIRECT
  - DOMAIN-SUFFIX, .cn, DIRECT
##########################
####      特定代理     ####
##########################
## Paypal
#  - DOMAIN-SUFFIX, paypal.com, PROXY
#  - DOMAIN-SUFFIX, paypalobjects.com, PROXY

##########################
####    开发相关服务    ####
##########################
## Flutter
  - DOMAIN-SUFFIX, dartlang.org, PROXY
  - DOMAIN-SUFFIX, flutter.dev, PROXY
  - DOMAIN-SUFFIX, flutter.io, PROXY
  - DOMAIN-SUFFIX, pub.dev, PROXY
  - DOMAIN-SUFFIX, dart.dev, PROXY
  - DOMAIN-SUFFIX, openai.com, PROXY
## Google Code
  - DOMAIN-SUFFIX, googlesource.com, PROXY
  - DOMAIN-SUFFIX, googlecode.com, PROXY
  - DOMAIN-SUFFIX, huobi.com, PROXY
## Github
  - DOMAIN-SUFFIX, github.com, PROXY
  - DOMAIN-SUFFIX, githubusercontent.com, PROXY
  - DOMAIN-SUFFIX, githubassets.com, PROXY
  - DOMAIN-SUFFIX, github.io, PROXY
  - DOMAIN-SUFFIX, git.io, PROXY

## Gradle
  - DOMAIN-SUFFIX, gradle.com, PROXY
  - DOMAIN-SUFFIX, gradle.org, PROXY

## Jetbrains
  - DOMAIN-SUFFIX, jetbrains.com, PROXY

## Jcenter
  - DOMAIN-SUFFIX, bintray.com, PROXY

## Jitpack
  - DOMAIN-SUFFIX, jitpack.io, PROXY

## Atlassian
  - DOMAIN-SUFFIX, atlassian.com, PROXY
  - DOMAIN-SUFFIX, bitbucket.org, PROXY
  - DOMAIN-SUFFIX, lithium.com, PROXY

## Docker
  - DOMAIN-SUFFIX, docker.com, PROXY
  - DOMAIN-SUFFIX, docker.io, PROXY

## Balena
  - DOMAIN-SUFFIX, balena.io, PROXY
  - DOMAIN-SUFFIX, balena-cloud.com, PROXY
  - DOMAIN-SUFFIX, discourse-cdn.com, PROXY

## NodeJS
  - DOMAIN-SUFFIX, nodejs.org, PROXY
  - DOMAIN-SUFFIX, npmjs.com, PROXY
  - DOMAIN-SUFFIX, yarnpkg.com, PROXY

## Sentry
  - DOMAIN-SUFFIX, sentry.io, PROXY
  - DOMAIN-SUFFIX, getsentry.net, PROXY
  - DOMAIN-SUFFIX, zendesk.com, PROXY
  - DOMAIN-SUFFIX, sentry-cdn.com, PROXY
  - DOMAIN-SUFFIX, stripe.com, PROXY
  - DOMAIN-SUFFIX, zdassets.com, PROXY

## Postman
  - DOMAIN-SUFFIX, pstmn.io, PROXY

## 其他
  - DOMAIN-SUFFIX, w3schools.com, PROXY
  - DOMAIN-SUFFIX, codeweavers.com, PROXY

##########################
####      云服务商     ####
##########################
## CDN
  - DOMAIN-SUFFIX, s3.amazonaws.com, PROXY
  - DOMAIN-SUFFIX, aws.amazonaws.com, PROXY
  - DOMAIN-SUFFIX, cloudflare.com, PROXY
  - DOMAIN-SUFFIX, cloudfront.net, PROXY
  - DOMAIN-SUFFIX, akamaihd.net, PROXY
#  - DOMAIN-SUFFIX, akamaized.net, PROXY
#  - DOMAIN-SUFFIX, fastly.net, PROXY
## GCP
  - DOMAIN-SUFFIX, appspot.com, PROXY
  - DOMAIN-SUFFIX, googleapis.com, PROXY
  - DOMAIN-SUFFIX, googleusercontent.com, PROXY

## Firebase
  - DOMAIN-SUFFIX, page.link, PROXY

## 阿里云
  - DOMAIN-SUFFIX, alibabacloud.com, PROXY
  - DOMAIN-SUFFIX, oss-us-west-1.aliyuncs.com, PROXY

## VPS
  - DOMAIN-SUFFIX, anchnet.com, PROXY
  - DOMAIN-SUFFIX, hostinger.com.hk, PROXY
  - DOMAIN-SUFFIX, bandwagonhost.com, PROXY
  - DOMAIN-SUFFIX, anynode.net, PROXY

  - DOMAIN-SUFFIX, oraclecloud.com, PROXY
  - DOMAIN-SUFFIX, godaddy.com, PROXY

##########################
####    Google全家桶   ####
##########################
## Google CN 直连
  - DOMAIN-SUFFIX, dl.google.com, PROXY

## *.google
  - DOMAIN-SUFFIX, google, PROXY

## Google CDN
  - DOMAIN-SUFFIX, ggpht.com, PROXY
  - DOMAIN-SUFFIX, gstatic.com, PROXY
  - DOMAIN-SUFFIX, gvt1.com, PROXY

## Google
  - DOMAIN-SUFFIX, goo.gl, PROXY
  - DOMAIN-SUFFIX, google.com, PROXY
  - DOMAIN-SUFFIX, google.co.jp, PROXY
  - DOMAIN-SUFFIX, google.com.hk, PROXY

## Gmail
  - DOMAIN-SUFFIX, gmail.com, PROXY

## YouTube
  - DOMAIN-SUFFIX, youtu.be, PROXY
  - DOMAIN-SUFFIX, youtube.com, PROXY
  - DOMAIN-SUFFIX, ytimg.com, PROXY
  - DOMAIN-SUFFIX, googlevideo.com, PROXY
  - DOMAIN-SUFFIX, youtube-nocookie.com, PROXY

## Blogger
  - DOMAIN-SUFFIX, blogger.com, PROXY
  - DOMAIN-SUFFIX, blogspot.com, PROXY

## Alphabet
  - DOMAIN-SUFFIX, withgoogle.com, PROXY
  - DOMAIN-SUFFIX, googleblog.com, PROXY

## Android
  - DOMAIN-SUFFIX, android.com, PROXY

## Material
  - DOMAIN-SUFFIX, material.io, PROXY

## Chromium
  - DOMAIN-SUFFIX, chromium.org, PROXY

##########################
####      视频网站     ####
##########################
## Hulu
  - DOMAIN-SUFFIX, hulu.com, PROXY
  - DOMAIN-SUFFIX, happyon.jp, PROXY

## Netflix
  - DOMAIN-SUFFIX, netflix.com, PROXY
  - DOMAIN-SUFFIX, nflxext.com, PROXY
  - DOMAIN-SUFFIX, nflxso.net, PROXY
  - DOMAIN-SUFFIX, nflximg.net, PROXY
  - DOMAIN-SUFFIX, nflxvideo.net, PROXY

##########################
####      社交代理     ####
##########################
## Telegram
  - DOMAIN-SUFFIX, t.me, PROXY
  - DOMAIN-SUFFIX, telegram.me, PROXY
  - DOMAIN-SUFFIX, telegram.org, PROXY
  - DOMAIN-SUFFIX, tdesktop.com, PROXY
  - IP-CIDR, 91.108.56.190/32, PROXY
  - IP-CIDR, 149.154.167.50/32, PROXY
  - IP-CIDR, 149.154.167.91/32, PROXY
  - IP-CIDR, 149.154.167.92/32, PROXY
  - IP-CIDR, 149.154.171.5/32, PROXY
  - IP-CIDR, 149.154.171.236/32, PROXY
  - IP-CIDR, 149.154.171.237/32, PROXY
  - IP-CIDR, 149.154.175.50/32, PROXY
  - IP-CIDR, 149.154.175.54/32, PROXY
  - IP-CIDR, 149.154.175.55/32, PROXY
  - IP-CIDR, 149.154.175.59/32, PROXY

## Twitter
  - DOMAIN-SUFFIX, t.co, PROXY
  - DOMAIN-SUFFIX, twitter.com, PROXY
  - DOMAIN-SUFFIX, twimg.com, PROXY

## Facebook
  - DOMAIN-SUFFIX, facebook.com, PROXY
#  - DOMAIN-SUFFIX, facebook.net, PROXY
## Tumblr
  - DOMAIN-SUFFIX, tumblr.com, PROXY

## LINE
  - DOMAIN-SUFFIX, line.me, PROXY
  - DOMAIN-SUFFIX, line.naver.jp, PROXY
  - DOMAIN-SUFFIX, line-scdn.net, PROXY

## imgur
  - DOMAIN-SUFFIX, imgur.com, PROXY

##########################
####        游戏       ####
##########################
## Supercell
  - DOMAIN-SUFFIX, brawlstars.com, PROXY
  - DOMAIN-SUFFIX, brawlstarsgame.com, PROXY
  - DOMAIN-SUFFIX, boombeachgame.com, PROXY
  - DOMAIN-SUFFIX, supercell.net, PROXY
  - DOMAIN-SUFFIX, supercell.helpshift.com, PROXY

## Zeptolab
  - DOMAIN-SUFFIX, zeptolab.com, PROXY
  - DOMAIN-SUFFIX, zeptodev.com, PROXY

## Rivio
  - DOMAIN-SUFFIX, rovio.com, PROXY
  - DOMAIN-SUFFIX, battlebay.net, PROXY

## Steam
  - DOMAIN-SUFFIX, steampowered.com, PROXY
  - DOMAIN-SUFFIX, steamcommunity.com, PROXY

##Epic
  - DOMAIN-SUFFIX, epicgames.com, PROXY
  - DOMAIN-SUFFIX, unrealengine.com, PROXY

## 育碧
  - DOMAIN-SUFFIX, ubi.com, PROXY
  - DOMAIN-SUFFIX, bhvronline.com, PROXY

## 光遇
  - DOMAIN-SUFFIX, live.radiance.thatgamecompany.com, PROXY

## Ingress
  - DOMAIN-SUFFIX, ingress.com, PROXY

##########################
####      常用服务     ####
##########################
## Microsoft
  - DOMAIN-SUFFIX, live.com, PROXY

## Mozilla
  - DOMAIN-SUFFIX, cdn.mozilla.net, PROXY
  - DOMAIN-SUFFIX, private-network.firefox.com, PROXY

## Amazon
  - DOMAIN-SUFFIX, amazon.co.jp, PROXY
  - DOMAIN-SUFFIX, amazon.com, PROXY

## Dropbox
  - DOMAIN-SUFFIX, dropbox.com, PROXY
  - DOMAIN-SUFFIX, dropboxapi.com, PROXY
  - DOMAIN-SUFFIX, dropboxstatic.com, PROXY
  - DOMAIN-SUFFIX, dropboxcaptcha.com, PROXY

## Spark
  - DOMAIN-SUFFIX, smartmailcloud.com, PROXY

## Medium
  - DOMAIN-SUFFIX, medium.com, PROXY

## Disqus
  - DOMAIN-SUFFIX, disqus.com, PROXY

## Reddit
  - DOMAIN-SUFFIX, reddit.com, PROXY
  - DOMAIN-SUFFIX, redditmedia.com, PROXY

## Quora
  - DOMAIN-SUFFIX, quora.com, PROXY

## Mega
  - DOMAIN-SUFFIX, mega.nz, PROXY

## Yandex
  - DOMAIN-SUFFIX, yandex.net, PROXY
  - DOMAIN-SUFFIX, yadi.sk, PROXY
  - DOMAIN-SUFFIX, yastatic.net, PROXY

## WiKi
  - DOMAIN-SUFFIX, wikipedia.org, PROXY
  - DOMAIN-SUFFIX, wikimedia.org, PROXY

## Jigsaw
  - DOMAIN-SUFFIX, digitalattackmap.com, PROXY

## UBNT
  - DOMAIN-SUFFIX, ubnt.com, PROXY

##OpenSUSE
  - DOMAIN-SUFFIX, opensuse.org, PROXY

## SpeedTest
  - DOMAIN-SUFFIX, speedtest.net, PROXY
  - DOMAIN-SUFFIX, adnxs.com, PROXY
  - DOMAIN-SUFFIX, cdnst.com, PROXY
  - DOMAIN-SUFFIX, cdnst.net, PROXY
  - DOMAIN-SUFFIX, ooklaserver.net, PROXY
  - DOMAIN-KEYWORD, speedtest, PROXY

## Fast
  - DOMAIN-SUFFIX, fast.com, PROXY

## IP Data
  - DOMAIN-SUFFIX, ipip.net, PROXY
  - DOMAIN-SUFFIX, ipinfo.io, PROXY

##########################
####       新闻       ####
##########################
### BBC
  - DOMAIN-SUFFIX, bbc.com, PROXY
  - DOMAIN-SUFFIX, bbc.co.uk, PROXY
  - DOMAIN-SUFFIX, bbci.co.uk, PROXY

## DWNEWS
  - DOMAIN-SUFFIX, dwnews.com, PROXY
  - DOMAIN-SUFFIX, dwnews.net, PROXY

##########################
####        VPN       ####
##########################
## Wireguard
  - DOMAIN-SUFFIX, wireguard.com, PROXY

## Shadowsocks
  - DOMAIN-SUFFIX, shadowsocks.org, PROXY

## V2ray
  - DOMAIN-SUFFIX, v2ray.com, PROXY

## OpenVPN
  - DOMAIN-SUFFIX, protonvpn.com, PROXY
  - DOMAIN-SUFFIX, openvpn.net, PROXY
  - DOMAIN-SUFFIX, ovpn.com, PROXY

##########################
####     个人Blog     ####
##########################
  - DOMAIN-SUFFIX, teddysun.com, PROXY
  - DOMAIN-SUFFIX, swsmile.info, PROXY

##########################
####        其他       ####
##########################
  - DOMAIN-SUFFIX, wireshark.org, PROXY
  - DOMAIN-SUFFIX, whatsmydnsserver.com, PROXY
  - DOMAIN-SUFFIX, code2flow.com, PROXY
  - DOMAIN-SUFFIX, zoomeye.org, PROXY
  - DOMAIN-SUFFIX, netgear.com, PROXY
  - DOMAIN-SUFFIX, sayori-static.com, PROXY
  - DOMAIN-SUFFIX, apkpure.com, PROXY
  - DOMAIN-SUFFIX, apkmirror.com, PROXY
  - DOMAIN-SUFFIX, winudf.com, PROXY
  - DOMAIN-SUFFIX, bit.ly, PROXY
  - DOMAIN-SUFFIX, pixiv.net, PROXY
  
## Porn
  - DOMAIN-SUFFIX, pornhub.com, PROXY
  - DOMAIN-SUFFIX, phncdn.com, PROXY
  - DOMAIN-SUFFIX, javmost.com, PROXY
  - DOMAIN-SUFFIX, avgle.com, PROXY
  - DOMAIN-SUFFIX, qooqlevideo.com, PROXY
  - DOMAIN-SUFFIX, fbcdn.net, PROXY
  - DOMAIN-SUFFIX, xvideos.com, PROXY
  - DOMAIN-SUFFIX, n.com, PROXY
  - DOMAIN-SUFFIX, 18xiangzi.com, PROXY
  - DOMAIN-SUFFIX, dmm.co.jp, PROXY



##########################
####       Final      ####
##########################
  - MATCH,DIRECT
